services:
    web:
        container_name: test_install_chat_web
        tty: true
        stdin_open: true
        build:
          context: .
        restart: always
        volumes:
            - .:/web
        ports:
            - 8000:8000
        env_file: .env
        command: bash -c "uvicorn test_install_chat.asgi:application --host 0.0.0.0 --port 8000"
    db:
        restart: always
        image: postgres:14.0
        environment:
          - POSTGRES_USER=test_install_chat
          - POSTGRES_PASSWORD=test_install_chat
          - POSTGRES_DB=test_install_chat
        expose:
          - 5432
        volumes:
          - "test_install_chat_db_data:/var/lib/postgresql/data"
        ports:
          - 5432:5432

    mailpit:
        image: axllent/mailpit
        volumes:
          - ./data:/data
        ports:
            - 1025:1025 # SMTP Server
            - 8025:8025 # Mailpit UI
        restart: unless-stopped
        environment:
              MP_MAX_MESSAGES: 5000
              MP_DATABASE: /data/mailpit.db
              MP_SMTP_AUTH_ACCEPT_ANY: 1
              MP_SMTP_AUTH_ALLOW_INSECURE: 1

    redis:
        container_name: test_install_chat_redis
        image: redis:alpine

    celery:
        container_name: test_install_chat_celery
        depends_on:
            - web
            - redis
        build:
          context: .
        restart: always
        volumes:
            - .:/web
        env_file: .env
        command: bash -c "celery -A test_install_chat worker --beat --loglevel=info"
volumes:
    test_install_chat_db_data:
