services:
  mailpit:
    image: axllent/mailpit
    container_name: mailpit-standalone
    volumes:
      - ./data:/data
    ports:
      - 1025:1025 # SMTP Server
      - 8025:8025 # Mailpit UI
    restart: unless-stopped
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
